name: CI
on:
  push:
    paths-ignore:
        - '*.md'
  pull_request:
    paths-ignore:
        - '*.md'
jobs:
  test:
    name: ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm i
      - name: Tests
        run: npm run ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: ${{ matrix.node-version == 16 }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          verbose: true

  automerge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
